//Get dogs
export const GET_DOGS_REQUEST = 'GET_DOGS_REQUEST';
export const GET_DOGS_SUCCESS = 'GET_DOGS_SUCCESS';
export const GET_DOGS_ERROR = 'GET_DOGS_ERROR';

//Search Dog
export const SEARCH_DOG_REQUEST = 'SEARCH_DOG_REQUEST';
export const SEARCH_DOG_SUCCESS = 'SEARCH_DOG_SUCCESS';
export const SEARCH_DOG_ERROR = 'SEARCH_DOG_ERROR';

//Get temperaments
export const GET_TEMPERAMENTS_REQUEST = 'GET_TEMPERAMENTS_REQUEST';
export const GET_TEMPERAMENTS_SUCCESS = 'GET_TEMPERAMENTS_SUCCESS';
export const GET_TEMPERAMENTS_ERROR = 'GET_TEMPERAMENTS_ERROR';

//Post user
export const POST_USER_REQUEST = 'POST_USER_REQUEST';
export const POST_USER_SUCCESS = 'POST_USER_SUCCESS';
export const POST_USER_ERROR = 'POST_USER_ERROR';

//Post favorite dog
export const POST_FAVORITE_REQUEST = 'POST_FAVORITE_REQUEST';
export const POST_FAVORITE_SUCCESS = 'POST_FAVORITE_SUCCESS';
export const POST_FAVORITE_ERROR = 'POST_FAVORITE_ERROR';

//Delete favorite dog
export const DELETE_FAVORITE_REQUEST = 'DELETE_FAVORITE_REQUEST';
export const DELETE_FAVORITE_SUCCESS = 'DELETE_FAVORITE_SUCCESS';
export const DELETE_FAVORITE_ERROR = 'DELETE_FAVORITE_ERROR';

//Get favorite dog
export const GET_FAVORITE_REQUEST = 'GET_FAVORITE_REQUEST';
export const GET_FAVORITE_SUCCESS = 'GET_FAVORITE_SUCCESS';
export const GET_FAVORITE_ERROR = 'GET_FAVORITE_ERROR';

//Post message
export const POST_MESSAGE_REQUEST = 'POST_MESSAGE_REQUEST';
export const POST_MESSAGE_SUCCESS = 'POST_MESSAGE_SUCCESS';
export const POST_MESSAGE_ERROR = 'POST_MESSAGE_ERROR';

//Get create dog
export const GET_CREATE_DOG_REQUEST = 'GET_CREATE_DOG_REQUEST';
export const GET_CREATE_DOG_SUCCESS = 'GET_CREATE_DOG_SUCCESS';
export const GET_CREATE_DOG_ERROR = 'GET_CREATE_DOG_ERROR';

//Clear data user
export const CLEAR_USER_DATA = 'CLEAR_USER_DATA';